In [ ]:
# Create class as Employee
class Employee:
  emp_count = 0

# Declaration and initialization of constructor
  def __init__(self, name, family, salary, department):

        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.emp_count = Employee.emp_count + 1

# Create function as avg_saal
  def avg_sal(self, emps):
      sum_sal = 0
      for i in emps:
            sum_sal= sum_sal+ i.salary

# Print output
      print(sum_sal/len(emps))

# Create class as Fulltime_Employee
class Fulltime_Employee(Employee):
  def __init__(self, name, family, salary, department):
         Employee.__init__(self, name, family, salary, department)

list = []
list.append(Employee('Priyatham', 'Swapna', 42000, 'Accounts'))
list.append(Employee('Gaddam', 'Sai Sri', 85000, 'Salesforce'))

list.append(Fulltime_Employee('Nithin', 'Disha', 65000, 'Architectutre'))
list.append(Fulltime_Employee('Eshwar', 'Diya', 30000, 'Management'))

list[0].avg_sal(list)
list[2].avg_sal(list)

# Print output as employee count
print(Employee.emp_count)

55500.0
55500.0
4


In [ ]:
import numpy as np

# Create random vector of size 20 with floats between 1 and 20
vec = np.random.uniform(1, 20, 20)

# Reshape the vector to 4 by 5
mat = vec.reshape(4, 5)

# Replace the max in each row by 0
mat[np.arange(4), mat.argmax(axis=1)] = 0

# Print output
print(mat)


[[ 5.62155118  1.52774492  0.         14.74653897  1.40187201]
 [ 0.          7.99424109  8.62663566  1.94042828  6.65579971]
 [ 0.         17.2640708   8.1233066   1.99161508  4.81157489]
 [10.94019001  4.10741978  0.          4.75043671  8.3344013 ]]
